# MobilePhone should have a method that returns a user's sim card number. SIM card number should be generated by a private method randomly.
# MobilePhone should have a method that returns the user's text balance.
# MobilePhone should have a method that returns the user's call balance.
# MobilePhone should allow a user to load more balance either their text or call.
# MobilePhone should allow a user to communicate either text or call. Return an error if there are insufficient load balance.
# Add an deduction rate attribute for sms with default 1. Should not be accessible to user.
# Add an deduction rate attribute for call with default 1.5. Should not be accessible to user.
# MobilePhone should have a method called sim_information that displays the user's SIM card number, call balance, deduction rates.
# A user should not be able to set any attributes from the MobilePhone class

class MobilePhone
    def initialize
        @sim_number = generate_number
        @text_balance = 10
        @call_balance = 10
        @text_deduction = 1
        @call_deduction = 1.5
    end
    def show_number
        @sim_number
    end
    def show_text_balance
        @text_balance
    end
    def show_call_balance
        @call_balance
    end
    def text
        @text_balance -= @text_deduction
        self
    end
    def call
        @call_balance -= @call_deduction
        self
    end
    def load_text(amount)
        @text_balance += amount
        self
    end
    def load_call(amount)
        @call_balance += amount
        self
    end 
    def sim_information
        puts "SIM number: #{show_number}. Call balance: #{show_call_balance}. Text balance: #{show_text_balance}"
    end
    private
        def generate_number
            ((1..9).collect {rand(9)}).join
        end
end

num = MobilePhone.new
num.text.text.load_text(5).sim_information